[app]
name = "translations"
version = "0.0.1"

[http]
addr = "0.0.0.0"
port = "8080"

[logger]
level = "debug"

[pg]
url = "postgres://postgres:Iam123@80.76.42.18:5432/smartri?sslmode=disable"
pool_max = 2

[jwt]
signing_string = "sfd$dsvk@sd!dsh"

[smtp]
username = "smartri.app@ya.ru"
password = "bqyghustpytdocdg"
host = "smtp.yandex.ru"
port = "587"
