[app]
name = "translations"
version = "0.0.1"

[http]
addr = "0.0.0.0"
port = ""

[pg]
user = ""
password = ""
host = ""
port = ""
database = ""
pool_max = "2"

[jwt]
signing_key = ""

[smtp]
username = ""
password = ""
host = "smtp.yandex.ru"
port = "587"
