app:
    name: "smartri"
    version: "0.0.1"
token_configuration:
    access_token_duration: 600 #10 minutes
    refresh_token_duration: 2592000 #month
http:
    addr: ""
    port: ""
pg:
    user: ""
    password: ""
    host: ""
    port: ""
    database: ""
    pool_max: "6"
redis:
    host: ""
    port: ""
    password: ""
    db: 0
jwt:
    signing_key: ""
smtp:
    username: ""
    password: ""
    host: "smtp.yandex.ru"
    port: "587"