version: '3.8'

services:
  postgres:
    container_name: "postgres"
    env_file:
      - ./authorization/.env
    build: ./authorization/migrations
    volumes:
      - database:/var/lib/postgresql/data
  auth:
    env_file:
      - ./authorization/.env
    build: ./authorization
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
  database: