version: '3.8'

services:
  auth_db:
    container_name: "auth_db"
    env_file:
      - .env
    build: ./authorization/database
#    volumes:
#      - database:/var/lib/postgresql/data
  api_gateway:
    container_name: "api_gateway"
    env_file:
      - .env
    build: ./api_gateway
    depends_on:
      - auth
    ports:
      - "8000:8000"
  auth:
    container_name: "auth"
    env_file:
      - .env
    build: ./authorization
    depends_on:
      - auth_db
#volumes:
#  database: