version: '3.8'

services:
  postgres:
    image: postgres
    volumes:
      - ./authorization/migrations/000001_create_user_table.up.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passssap
    ports:
      - "5432:5432"
    restart: unless-stopped
  auth:
    build: ./authorization
    depends_on:
      - postgres
    ports:
      - "8080:8080"