version: '3.8'

services:
  api_gateway:
    container_name: "api_gateway"
    env_file:
      - ./api_gateway/gateway.env
      - ./authorization/auth.env
      - ./application/application.env
    build: ./api_gateway
    depends_on:
      - auth
    ports:
      - "8000:8000"


  auth:
    container_name: "auth"
    env_file:
      - ./authorization/auth.env
    build: ./authorization
    depends_on:
      - auth_db
  auth_db:
    container_name: "auth_db"
    env_file:
      - authorization/auth.env
    build: ./authorization/pkg/postgres
    volumes:
      - database:/var/lib/postgresql/data
  auth_redis:
    container_name: "auth_redis"
    env_file:
      - authorization/auth.env
    build: ./authorization/pkg/redis


  application:
    container_name: "application"
    env_file:
      - ./application/application.env
    build: ./application
    depends_on:
      - application_db
  application_db:
    container_name: "application_db"
    env_file:
      - ./application/application.env
    build: ./application/pkg/postgres
    volumes:
      - auth:/var/lib/postgresql/data

volumes:
  database:
  auth: