definitions:
  v1.createUserRequest:
    properties:
      e-mail:
        example: shilo@milo.psih
        type: string
      login:
        example: TopPlayer123
        type: string
      nickname:
        example: Looser1123
        type: string
      password:
        example: 123superPassword
        type: string
    required:
    - e-mail
    - login
    - nickname
    - password
    type: object
  v1.createUserResponse:
    properties:
      id:
        example: 2
        type: integer
    type: object
  v1.response:
    properties:
      code:
        type: string
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/:
    post:
      consumes:
      - application/json
      operationId: history
      parameters:
      - description: Data for registration
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.createUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.createUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Create user
swagger: "2.0"
